name: prod

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: prod
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  quality:
    uses: ./.github/workflows/checks.yml

  deploy:
    needs: quality
    uses: ./.github/workflows/release.yml
    with:
      environment: prod
      build: false
    permissions:
      contents: read
      id-token: write
